const workday = (key, name, careersUrl, boards, careerPath = null) => ({
  key, name, companyId: key, universe: "buy-side", careerPath, provider: "Workday",
  careersUrl, adapter: "workday", config: { boards },
});

const official = (key, name, careersUrl, careerPath = null, options = {}) => ({
  key, name, companyId: key, universe: "buy-side", careerPath,
  provider: options.provider ?? "Official careers page", careersUrl,
  adapter: "static-careers",
  config: {
    pageUrls: options.pageUrls ?? [careersUrl],
    defaultLocation: options.defaultLocation,
    metadataText: options.metadataText ?? "",
    contextText: options.contextText ?? "",
    allowHomeRoleParsing: options.allowHomeRoleParsing ?? false,
  },
});

export const BUYSIDE_FIRMS = [
  workday("cpp-investments", "CPP Investments", "https://www.cppinvestments.com/careers/", [{ host: "https://cppib.wd10.myworkdayjobs.com", tenant: "cppib", site: "cppinvestments" }], "Institutional Investing"),
  official("la-caisse", "La Caisse (CDPQ)", "https://www.lacaisse.com/en/careers/job-opportunities", "Institutional Investing"),
  workday("ontario-teachers", "Ontario Teachers' Pension Plan", "https://www.otpp.com/en-ca/careers/", [{ host: "https://otppb.wd3.myworkdayjobs.com", tenant: "otppb", site: "OntarioTeachers_Careers" }], "Institutional Investing"),
  workday("bci", "BCI", "https://www.bci.ca/careers/", [{ host: "https://bci.wd10.myworkdayjobs.com", tenant: "bci", site: "BCI_Careers" }], "Institutional Investing"),
  workday("psp-investments", "PSP Investments", "https://www.investpsp.com/en/careers/", [{ host: "https://investpsp.wd3.myworkdayjobs.com", tenant: "investpsp", site: "psp_careers" }], "Institutional Investing"),
  workday("omers", "OMERS", "https://www.omers.com/careers", [{ host: "https://omers.wd3.myworkdayjobs.com", tenant: "omers", site: "OMERS_External" }], "Institutional Investing"),
  workday("aimco", "AIMCo", "https://www.aimco.ca/careers", [{ host: "https://aimco.wd10.myworkdayjobs.com", tenant: "aimco", site: "AIMCoCareers" }], "Institutional Investing"),
  workday("hoopp", "HOOPP", "https://hoopp.com/careers", [{ host: "https://hoopp.wd10.myworkdayjobs.com", tenant: "hoopp", site: "HOOPP" }], "Institutional Investing"),
  official("optrust", "OPTrust", "https://optrust.com/careers", "Institutional Investing"),
  official("ontario-pension-board", "Ontario Pension Board", "https://www.opb.ca/employment-opportunities", "Institutional Investing"),
  workday("imco", "IMCO", "https://www.imcoinvest.com/careers", [{ host: "https://imcoinvest.wd3.myworkdayjobs.com", tenant: "imcoinvest", site: "IMCO" }], "Institutional Investing"),

  workday("brookfield-asset-management", "Brookfield Asset Management", "https://www.brookfield.com/careers", [{ host: "https://brookfield.wd5.myworkdayjobs.com", tenant: "brookfield", site: "brookfield" }], "Private Equity"),
  official("onex", "Onex", "https://www.onex.com/careers", "Private Equity"),
  official("altas-partners", "Altas Partners", "https://www.altaspartners.com/careers", "Private Equity"),
  official("birch-hill-equity-partners", "Birch Hill Equity Partners", "https://www.birchhillequity.com/careers/", "Private Equity"),
  official("clairvest", "Clairvest", "https://www.clairvest.com/careers/", "Private Equity"),
  official("northleaf-capital", "Northleaf Capital Partners", "https://www.northleafcapital.com/careers/", "Private Equity"),
  official("novacap", "Novacap", "https://novacap.ca/careers/", "Private Equity"),
  official("torquest", "TorQuest Partners", "https://www.torquest.com/careers/", "Private Equity"),
  official("imperial-capital", "Imperial Capital", "https://imperialcap.com/careers/", "Private Equity"),
  official("peloton-capital", "Peloton Capital Management", "https://pelotoncapitalmanagement.com/careers/", "Private Equity"),
  official("kensington-capital", "Kensington Capital Partners", "https://www.kcpl.ca/careers", "Private Equity"),
  official("triwest-capital", "TriWest Capital Partners", "https://triwest.ca/careers/", "Private Equity"),
  official("ironbridge-equity", "Ironbridge Equity Partners", "https://www.ironbridgeequity.com/careers/", "Private Equity"),
  official("oncap", "ONCAP", "https://www.oncap.com/careers", "Private Equity"),

  official("phn", "Phillips, Hager & North", "https://jobs.rbc.com/ca/en/c/asset-management-jobs", "Asset Management"),
  official("burgundy-asset-management", "Burgundy Asset Management", "https://www.burgundyasset.com/careers/", "Asset Management"),
  official("mawer", "Mawer Investment Management", "https://www.mawer.com/careers/", "Asset Management"),
  official("ccl", "Connor, Clark & Lunn Financial Group", "https://www.cclgroup.com/careers/career-opportunities/", "Asset Management"),
  official("fiera-capital", "Fiera Capital", "https://careers.fieracapital.com/", "Asset Management"),
  official("cadillac-fairview", "Cadillac Fairview", "https://careers.cadillacfairview.com/", "Real Estate Investing"),
  official("quadreal", "QuadReal", "https://www.quadreal.com/careers", "Real Estate Investing"),
  official("slate-asset-management", "Slate Asset Management", "https://www.slateam.com/careers/", "Real Estate Investing"),
  official("beutel-goodman", "Beutel Goodman", "https://www.beutelgoodman.com/careers/", "Asset Management"),
  official("agf-investments", "AGF Investments", "https://www.agf.com/ca/en/about-agf/careers/index.jsp", "Asset Management"),
  workday("ci-financial", "CI Financial", "https://www.cifinancial.com/careers", [{ host: "https://ci.wd3.myworkdayjobs.com", tenant: "ci", site: "CI_FINANCIAL_EXTERNAL_CAREER-SITE" }], "Asset Management"),
  official("letko-brosseau", "Letko Brosseau", "https://www.lba.ca/careers/", "Asset Management"),
  official("edgepoint", "EdgePoint Investment Group", "https://edgepointwealth.com/en/about-us/careers/", "Asset Management"),
  official("purpose-investments", "Purpose Investments", "https://www.purposeinvest.com/careers", "Asset Management"),
  official("dynamic-funds", "Dynamic Funds / 1832 Asset Management", "https://jobs.scotiabank.com/go/Asset-Management/2296817/", "Asset Management"),
  official("jarislowsky-fraser", "Jarislowsky Fraser", "https://www.jflglobal.com/careers", "Asset Management"),
  official("guardian-capital", "Guardian Capital", "https://www.guardiancapital.com/careers/", "Asset Management"),
  official("deans-knight", "Deans Knight Capital Management", "https://www.deansknight.com/careers/", "Asset Management"),
  official("ninepoint", "Ninepoint Partners", "https://ninepoint.com/about-us/careers/", "Asset Management"),
  official("ewing-morris", "Ewing Morris", "https://www.ewingmorris.com/careers", "Asset Management"),
  official("mackenzie-investments", "Mackenzie Investments", "https://www.mackenzieinvestments.com/en/about-us/careers", "Asset Management"),
  official("ia-clarington", "IA Clarington Investments", "https://iaclarington.com/careers", "Asset Management"),
  official("md-management", "MD Financial Management", "https://mdm.ca/about-md/careers", "Asset Management"),
  official("canoe-financial", "Canoe Financial", "https://www.canoefinancial.com/careers/", "Asset Management"),
  official("franklin-templeton", "Franklin Templeton / Franklin Bissett", "https://www.franklintempletoncareers.com/", "Asset Management"),
  official("td-asset-management", "TD Asset Management", "https://jobs.td.com/en-CA/job-opportunities/", "Asset Management"),
  official("cibc-asset-management", "CIBC Asset Management / Renaissance", "https://www.cibc.com/en/about-cibc/careers.html", "Asset Management"),
  official("bmo-capital-partners", "BMO Capital Partners", "https://jobs.bmo.com/ca/en", "Private Equity"),

  official("polar-asset-management", "Polar Asset Management", "https://polaramp.com/careers/", "Hedge Fund"),
  official("waratah-advisors", "Waratah Advisors", "https://waratahadvisors.com/careers/", "Hedge Fund"),
  official("catalyst-capital", "Catalyst Capital Group", "https://www.catcapital.com/careers/", "Hedge Fund"),
  official("turtle-creek", "Turtle Creek Asset Management", "https://www.turtlecreek.ca/careers/", "Hedge Fund"),
  official("maple-rock", "Maple Rock Capital Partners", "https://www.maplerockcapital.com/careers", "Hedge Fund"),
  official("sprott", "Sprott", "https://sprott.com/about-us/careers/", "Asset Management"),
  official("picton-mahoney", "Picton Mahoney Asset Management", "https://www.pictonmahoney.com/careers/", "Hedge Fund"),
  official("stonepine", "Stonepine Asset Management", "https://www.stonepine.com/careers", "Hedge Fund"),
  official("crimson-asset-management", "Crimson Asset Management", "https://www.crimsonasset.com/careers", "Hedge Fund"),
  official("citadel", "Citadel", "https://www.citadel.com/careers/open-positions/", "Hedge Fund"),
  official("point72", "Point72", "https://careers.point72.com/", "Hedge Fund"),
  official("balyasny", "Balyasny Asset Management", "https://www.bamfunds.com/careers", "Hedge Fund"),
  official("k2-associates", "K2 & Associates", "https://www.k2.ca/careers", "Hedge Fund"),

  workday("fengate", "Fengate Asset Management", "https://fengate.com/careers/", [{ host: "https://fengate.wd10.myworkdayjobs.com", tenant: "fengate", site: "Fengate_Careers" }], "Private Equity"),
  official("manulife-investment-management", "Manulife Investment Management", "https://careers.manulife.com/", "Asset Management"),
  official("crestpoint", "Crestpoint Real Estate Investments", "https://www.cclgroup.com/careers/career-opportunities/", "Real Estate Investing"),
  official("upp", "University Pension Plan Ontario", "https://myupp.ca/careers/", "Institutional Investing"),
  official("canada-infrastructure-bank", "Canada Infrastructure Bank", "https://cib-bic.ca/en/careers/", "Institutional Investing"),
  official("choice-properties", "Choice Properties REIT", "https://www.choicereit.ca/careers/", "Real Estate Investing"),
  official("capreit", "CAPREIT", "https://www.capreit.ca/careers/", "Real Estate Investing"),
  official("anson-funds", "Anson Funds", "https://www.ansonfunds.com/careers", "Hedge Fund"),
  official("nicola-wealth", "Nicola Wealth", "https://nicolawealth.com/careers/", "Asset Management"),
];
