"use client";

import { ArrowUpRight, BriefcaseBusiness, ChevronDown, MapPin, Search, X } from "lucide-react";
import { useMemo, useState } from "react";

type Job = { company:string; title:string; location:string; category:string; seniority:string; program:string; deadline:string|null; url:string; summary:string };
const jobs: Job[] = [
  ["BDO Canada","Co-op or Intern, M&A and Capital Markets — January 2027","Toronto, ON","Transaction Advisory","Intern","Co-op / Internship","2026-09-14","https://bdo.wd3.myworkdayjobs.com/en-US/BDO/job/Toronto---Bay-St/Co-op-or-Intern--M-A-and-Capital-Markets---January-2027_JR6802","Support BDO's M&A and Capital Markets work in a fast-paced deals environment."],
  ["RBC Capital Markets","Global Investment Banking, Real Estate — Winter Analyst","Toronto, ON","Investment Banking","Analyst","Student / Co-op","2026-09-15","https://jobs.rbc.com/ca/en/job/RBCAA0088R0000187031EXTERNALENCA/2027-Capital-Markets-Global-Investment-Banking-Real-Estate-Property-Brokerage-Winter-Analyst-4-Months","Four-month placement supporting RBC's real estate brokerage team with research, investment materials and valuation models."],
  ["CIBC","Global Markets, Winter 2027 Analyst","Toronto, ON","Markets","Analyst","Co-op","2026-09-18","https://cibc.wd3.myworkdayjobs.com/campus/job/Toronto-ON/Global-Markets--Winter-2027-Analyst--8-months-_2618392-1","Eight-month placement across sales, trading, structuring and research."],
  ["BMO Capital Markets","Investment Banking Analyst, Real Estate Brokerage — Winter 2027","Toronto, ON","Investment Banking","Analyst","Co-op / Internship","2026-09-20","https://bmo.wd3.myworkdayjobs.com/en-US/External/job/Toronto-ON-CAN/BMO-Capital-Markets-Winter-2027-Investment-Banking-Analyst--Real-Estate-Brokerage--Toronto_R260021697-1","Winter placement supporting analysis and transaction execution in Real Estate Brokerage."],
  ["Questrade Financial Group","Strategy & Corporate Development Intern","Toronto, ON","Corporate Development","Intern","Internship","2026-09-21","https://jobs.dayforcehcm.com/en-US/qfg/CANDIDATEPORTAL/jobs/17629","Fourteen-week internship supporting enterprise strategy, investment evaluation and strategic projects."],
  ["ATB Capital Markets","Investment Banking Summer Student, Mining","Toronto, ON","Investment Banking","Intern","Internship","2026-09-23","https://careers.atb.com/careers/job/1125899907733808","Summer 2027 student role supporting the Mining investment banking team."],
  ["BMO Capital Markets","Investment Banking Analyst, Metals & Mining — Winter 2027","Toronto, ON","Investment Banking","Analyst","Co-op / Internship","2026-09-24","https://bmo.wd3.myworkdayjobs.com/en-US/External/job/Toronto-ON-CAN/BMO-Capital-Markets-Winter-2027-Investment-Banking-Analyst--Metals---Mining--Toronto_R260021761-1","Support valuation, transaction execution and client materials in Metals & Mining."],
  ["Scotiabank","Velocity — Mergers & Acquisitions Internship/Co-op","Toronto, ON","Corporate Development","Intern","Co-op / Internship","2026-09-25","https://jobs.scotiabank.com/job/Toronto-Velocity-Mergers-&-Acquisitions-InternshipCo-op-Winter-2027-ON/605717017/","Support acquisitions, divestitures, valuations, due diligence and capital-allocation projects."],
  ["Alvarez & Marsal","Analyst, Corporate Finance","Toronto, ON","Investment Banking","Analyst","Full-time",null,"https://careers.alvarezandmarsal.com/jobs/18014934-analyst-restructuring","Support restructurings, M&A, valuations, financial modelling and client execution."],
  ["Morgan Stanley","Canada Investment Banking Analyst","Toronto, ON","Investment Banking","Analyst","Full-time",null,"https://morganstanley.eightfold.ai/careers/job/549798030828","Cover Canadian clients across industries, including M&A and equity and debt financings."],
  ["Rothschild & Co","Global Advisory, Metals & Mining, Junior Associate","Toronto, ON","Investment Banking","Associate","Full-time",null,"https://rothschildandco.wd3.myworkdayjobs.com/RothschildAndCo_Lateral/job/Toronto/Global-Advisory--Metals---Mining--Junior-Associate--Toronto_JR015548-1","Junior Associate role in the Global Advisory Metals & Mining team."],
  ["Ventum Financial","Investment Banking Analyst","Toronto, ON","Investment Banking","Analyst","Full-time",null,"https://workforcenow.adp.com/mascsr/default/mdf/recruitment/recruitment.html?cid=6c06ce68-5388-4357-97c9-9f1c3ceb45dc&ccId=19000101_000001&jobId=636560&lang=en_CA","Generalist role supporting capital raising, M&A, debt capital markets and financial modelling."],
  ["Agentis Capital Advisors","Investment Banking Analyst — Infrastructure M&A Advisory","Toronto or Vancouver","Investment Banking","Analyst","Full-time",null,"https://jobs.ashbyhq.com/Agentis-Capital-Advisors/d5e656b2-ddf0-4431-b051-3cc425d3245a","Infrastructure advisory role involving M&A, offerings, partnerships, due diligence and modelling."],
  ["BMO Capital Markets","Investment Banking Analyst, Mergers & Acquisitions","Toronto, ON","Investment Banking","Analyst","Full-time",null,"https://bmo.wd3.myworkdayjobs.com/en-US/External/job/Toronto-ON-CAN/Investment-Banking-Analyst--Merger-and-Acquisitions--M-A-_R260024682","Support acquisitions, divestitures, strategic investments and other transactions."],
  ["BMO Capital Markets","Investment Banking Analyst, Technology","Toronto, ON","Investment Banking","Analyst","Full-time",null,"https://bmo.wd3.myworkdayjobs.com/en-US/External/job/Toronto-ON-CAN/Investment-Banking-Analyst--Technology_R260025058","Support technology industry coverage, analysis and transaction execution."],
].map(([company,title,location,category,seniority,program,deadline,url,summary]) => ({company,title,location,category,seniority,program,deadline,url,summary})) as Job[];

const fmt = (date:string|null) => date ? new Intl.DateTimeFormat("en-CA",{month:"short",day:"numeric"}).format(new Date(`${date}T12:00:00`)) : "Open";

export default function Home() {
  const [query,setQuery]=useState(""); const [category,setCategory]=useState("All fields"); const [program,setProgram]=useState("All roles"); const [selected,setSelected]=useState<Job|null>(null);
  const categories=["All fields",...Array.from(new Set(jobs.map(j=>j.category)))]; const programs=["All roles",...Array.from(new Set(jobs.map(j=>j.program)))];
  const filtered=useMemo(()=>jobs.filter(j=>`${j.company} ${j.title} ${j.category} ${j.location}`.toLowerCase().includes(query.toLowerCase())&&(category==="All fields"||j.category===category)&&(program==="All roles"||j.program===program)),[query,category,program]);
  return <main>
    <header className="site-header"><a className="brand" href="#top"><span className="brand-mark">BSO</span><span className="brand-name">BAY STREET ORACLE</span><span className="brand-product">JOBS</span></a><nav><a href="#jobs">Browse jobs</a><a href="#about">About</a></nav></header>
    <section className="masthead" id="top"><div><p className="eyebrow">Canada&apos;s finance career board</p><h1>Find your next seat<br/>on Bay Street.</h1></div><p className="intro">Curated opportunities in investment banking, markets, private capital and corporate finance.</p></section>
    <section className="filter-wrap"><div className="search-band"><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search title, company or field" aria-label="Search jobs"/><span>{filtered.length} roles</span></div><div className="select-row"><label><span>Field</span><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(v=><option key={v}>{v}</option>)}</select><ChevronDown size={15}/></label><label><span>Type</span><select value={program} onChange={e=>setProgram(e.target.value)}>{programs.map(v=><option key={v}>{v}</option>)}</select><ChevronDown size={15}/></label>{(query||category!=="All fields"||program!=="All roles")&&<button onClick={()=>{setQuery("");setCategory("All fields");setProgram("All roles")}}><X size={14}/> Clear</button>}</div></section>
    <section className="jobs-section" id="jobs"><aside><p className="eyebrow">Open roles</p><h2>Fresh opportunities, without the noise.</h2><p>Every role is reviewed and linked directly to the employer.</p></aside><div className="job-list">{filtered.map(job=><article className="job-card" key={`${job.company}-${job.title}`} onClick={()=>setSelected(job)}><div className="company-monogram">{job.company.split(" ").map(w=>w[0]).slice(0,2).join("")}</div><div className="job-copy"><p className="company">{job.company}</p><h3>{job.title}</h3><div className="meta"><span><MapPin size={14}/>{job.location}</span><span><BriefcaseBusiness size={14}/>{job.program}</span></div><span className="category">{job.category}</span></div><div className="job-action"><p>{job.deadline?"Apply by":"Deadline"} <strong>{fmt(job.deadline)}</strong></p><button onClick={e=>{e.stopPropagation();setSelected(job)}}>View role <ArrowUpRight size={15}/></button></div></article>)}{!filtered.length&&<div className="empty">No roles match those filters yet.</div>}</div></section>
    <footer id="about"><span>BSO JOBS</span><p>Built for ambitious Canadians entering finance.</p><span>Toronto, Canada</span></footer>
    {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="job-modal" onClick={e=>e.stopPropagation()} role="dialog" aria-modal="true"><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Close"><X/></button><p className="eyebrow">{selected.company}</p><h2>{selected.title}</h2><div className="modal-meta"><span><MapPin size={15}/>{selected.location}</span><span><BriefcaseBusiness size={15}/>{selected.program}</span></div><p className="modal-summary">{selected.summary}</p><dl><div><dt>Field</dt><dd>{selected.category}</dd></div><div><dt>Level</dt><dd>{selected.seniority}</dd></div><div><dt>Deadline</dt><dd>{fmt(selected.deadline)}</dd></div></dl><a className="apply-button" href={selected.url} target="_blank" rel="noreferrer">Apply on employer site <ArrowUpRight size={18}/></a></section></div>}
  </main>;
}
