"use client";

import { ArrowRight, ArrowUpRight, BriefcaseBusiness, Building2, ChevronDown, Clock3, Mail, MapPin, Search, Sparkles, X } from "lucide-react";
import { ReactNode, useEffect, useMemo, useRef, useState } from "react";

type Job = { company:string; title:string; location:string; category:string; seniority:string; program:string; deadline:string|null; url:string; summary:string };

const jobs: Job[] = [
  ["BDO Canada","Co-op or Intern, M&A and Capital Markets — January 2027","Toronto, ON","Transaction Advisory","Intern","Co-op / Internship","2026-09-14","https://bdo.wd3.myworkdayjobs.com/en-US/BDO/job/Toronto---Bay-St/Co-op-or-Intern--M-A-and-Capital-Markets---January-2027_JR6802","Support BDO's M&A and Capital Markets work in a fast-paced deals environment."],
  ["RBC Capital Markets","Global Investment Banking, Real Estate — Winter Analyst","Toronto, ON","Investment Banking","Analyst","Student / Co-op","2026-09-15","https://jobs.rbc.com/ca/en/job/RBCAA0088R0000187031EXTERNALENCA/2027-Capital-Markets-Global-Investment-Banking-Real-Estate-Property-Brokerage-Winter-Analyst-4-Months","Four-month placement supporting RBC's real estate brokerage team with research, investment materials and valuation models."],
  ["CIBC","Global Markets, Winter 2027 Analyst","Toronto, ON","Markets","Analyst","Co-op","2026-09-18","https://cibc.wd3.myworkdayjobs.com/campus/job/Toronto-ON/Global-Markets--Winter-2027-Analyst--8-months-_2618392-1","Eight-month placement across sales, trading, structuring and research."],
  ["BMO Capital Markets","Investment Banking Analyst, Real Estate Brokerage — Winter 2027","Toronto, ON","Investment Banking","Analyst","Co-op / Internship","2026-09-20","https://bmo.wd3.myworkdayjobs.com/en-US/External/job/Toronto-ON-CAN/BMO-Capital-Markets-Winter-2027-Investment-Banking-Analyst--Real-Estate-Brokerage--Toronto_R260021697-1","Winter placement supporting analysis and transaction execution in Real Estate Brokerage."],
  ["Questrade Financial Group","Strategy & Corporate Development Intern","Toronto, ON","Corporate Development","Intern","Internship","2026-09-21","https://jobs.dayforcehcm.com/en-US/qfg/CANDIDATEPORTAL/jobs/17629","Fourteen-week internship supporting enterprise strategy, investment evaluation and strategic projects."],
  ["ATB Capital Markets","Investment Banking Summer Student, Mining","Toronto, ON","Investment Banking","Intern","Internship","2026-09-23","https://careers.atb.com/careers/job/1125899907733808","Summer 2027 student role supporting the Mining investment banking team."],
  ["BMO Capital Markets","Investment Banking Analyst, Metals & Mining — Winter 2027","Toronto, ON","Investment Banking","Analyst","Co-op / Internship","2026-09-24","https://bmo.wd3.myworkdayjobs.com/en-US/External/job/Toronto-ON-CAN/BMO-Capital-Markets-Winter-2027-Investment-Banking-Analyst--Metals---Mining--Toronto_R260021761-1","Support valuation, transaction execution and client materials in Metals & Mining."],
  ["Scotiabank","Velocity — Mergers & Acquisitions Internship/Co-op","Toronto, ON","Corporate Development","Intern","Co-op / Internship","2026-09-25","https://jobs.scotiabank.com/job/Toronto-Velocity-Mergers-&-Acquisitions-InternshipCo-op-Winter-2027-ON/605717017/","Support acquisitions, divestitures, valuations, due diligence and capital-allocation projects."],
  ["Alvarez & Marsal","Analyst, Corporate Finance","Toronto, ON","Investment Banking","Analyst","Full-time",null,"https://careers.alvarezandmarsal.com/jobs/18014934-analyst-restructuring","Support restructurings, M&A, valuations, financial modelling and client execution."],
  ["Morgan Stanley","Canada Investment Banking Analyst","Toronto, ON","Investment Banking","Analyst","Full-time",null,"https://morganstanley.eightfold.ai/careers/job/549798030828","Cover Canadian clients across industries, including M&A and equity and debt financings."],
  ["Rothschild & Co","Global Advisory, Metals & Mining, Junior Associate","Toronto, ON","Investment Banking","Associate","Full-time",null,"https://rothschildandco.wd3.myworkdayjobs.com/RothschildAndCo_Lateral/job/Toronto/Global-Advisory--Metals---Mining--Junior-Associate--Toronto_JR015548-1","Junior Associate role in the Global Advisory Metals & Mining team."],
  ["Ventum Financial","Investment Banking Analyst","Toronto, ON","Investment Banking","Analyst","Full-time",null,"https://workforcenow.adp.com/mascsr/default/mdf/recruitment/recruitment.html?cid=6c06ce68-5388-4357-97c9-9f1c3ceb45dc&ccId=19000101_000001&jobId=636560&lang=en_CA","Generalist role supporting capital raising, M&A, debt capital markets and financial modelling."],
  ["Agentis Capital Advisors","Investment Banking Analyst — Infrastructure M&A Advisory","Toronto or Vancouver","Investment Banking","Analyst","Full-time",null,"https://jobs.ashbyhq.com/Agentis-Capital-Advisors/d5e656b2-ddf0-4431-b051-3cc425d3245a","Infrastructure advisory role involving M&A, offerings, partnerships, due diligence and modelling."],
  ["BMO Capital Markets","Investment Banking Analyst, Mergers & Acquisitions","Toronto, ON","Investment Banking","Analyst","Full-time",null,"https://bmo.wd3.myworkdayjobs.com/en-US/External/job/Toronto-ON-CAN/Investment-Banking-Analyst--Merger-and-Acquisitions--M-A-_R260024682","Support acquisitions, divestitures, strategic investments and other transactions."],
  ["BMO Capital Markets","Investment Banking Analyst, Technology","Toronto, ON","Investment Banking","Analyst","Full-time",null,"https://bmo.wd3.myworkdayjobs.com/en-US/External/job/Toronto-ON-CAN/Investment-Banking-Analyst--Technology_R260025058","Support technology industry coverage, analysis and transaction execution."],
].map(([company,title,location,category,seniority,program,deadline,url,summary]) => ({company,title,location,category,seniority,program,deadline,url,summary})) as Job[];

const domains: Record<string,string> = {
  "BDO Canada":"bdo.ca", "RBC Capital Markets":"rbccm.com", "CIBC":"cibc.com", "BMO Capital Markets":"bmo.com", "Questrade Financial Group":"questrade.com", "ATB Capital Markets":"atb.com", "Scotiabank":"scotiabank.com", "Alvarez & Marsal":"alvarezandmarsal.com", "Morgan Stanley":"morganstanley.com", "Rothschild & Co":"rothschildandco.com", "Ventum Financial":"ventumfinancial.com", "Agentis Capital Advisors":"agentis.ca"
};
const companyType: Record<string,string> = {"BDO Canada":"Advisory","RBC Capital Markets":"Canadian bank","CIBC":"Canadian bank","BMO Capital Markets":"Canadian bank","Questrade Financial Group":"Financial services","ATB Capital Markets":"Independent dealer","Scotiabank":"Canadian bank","Alvarez & Marsal":"Advisory","Morgan Stanley":"Global bank","Rothschild & Co":"Global advisory","Ventum Financial":"Independent dealer","Agentis Capital Advisors":"Independent advisory"};
const companies = Object.keys(domains).map(name=>({name,domain:domains[name],type:companyType[name],count:jobs.filter(j=>j.company===name).length}));
const logo = (company:string) => `https://www.google.com/s2/favicons?domain=${domains[company]}&sz=128`;
const fmt = (date:string|null) => date ? new Intl.DateTimeFormat("en-CA",{month:"short",day:"numeric"}).format(new Date(`${date}T12:00:00`)) : "Open";

function Reveal({children,className="",delay=0}:{children:ReactNode;className?:string;delay?:number}) {
  const ref=useRef<HTMLDivElement>(null);
  useEffect(()=>{const node=ref.current;if(!node)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){node.classList.add("is-visible");observer.disconnect();}},{threshold:.12});observer.observe(node);return()=>observer.disconnect();},[]);
  return <div ref={ref} className={`reveal ${className}`} style={{transitionDelay:`${delay}ms`}}>{children}</div>;
}

function CompanyLogo({company,size="small"}:{company:string;size?:"small"|"large"}) {
  const [failed,setFailed]=useState(false);
  return <div className={`company-logo ${size}`}>{failed?<span>{company.split(" ").map(w=>w[0]).slice(0,2).join("")}</span>:<img src={logo(company)} alt={`${company} logo`} onError={()=>setFailed(true)}/>}</div>;
}

export default function Home() {
  const [query,setQuery]=useState(""); const [category,setCategory]=useState("All fields"); const [program,setProgram]=useState("All roles"); const [selected,setSelected]=useState<Job|null>(null); const [companyFilter,setCompanyFilter]=useState<string|null>(null); const [menuOpen,setMenuOpen]=useState(false); const [subscribed,setSubscribed]=useState(false);
  const categories=["All fields",...Array.from(new Set(jobs.map(j=>j.category)))]; const programs=["All roles",...Array.from(new Set(jobs.map(j=>j.program)))];
  const filtered=useMemo(()=>jobs.filter(j=>`${j.company} ${j.title} ${j.category} ${j.location}`.toLowerCase().includes(query.toLowerCase())&&(category==="All fields"||j.category===category)&&(program==="All roles"||j.program===program)&&(!companyFilter||j.company===companyFilter)),[query,category,program,companyFilter]);
  const reset=()=>{setQuery("");setCategory("All fields");setProgram("All roles");setCompanyFilter(null)};
  const chooseCompany=(name:string)=>{reset();setCompanyFilter(name);document.querySelector("#jobs")?.scrollIntoView({behavior:"smooth"})};

  return <main>
    <header className="site-header"><a className="brand" href="#top"><img className="brand-logo" src="/bso-logo.png" alt="Bay Street Oracle"/><span className="brand-name">BAY STREET ORACLE</span><span className="brand-product">JOBS</span></a><nav className={menuOpen?"open":""}><a href="#jobs" onClick={()=>setMenuOpen(false)}>Jobs</a><a href="#companies" onClick={()=>setMenuOpen(false)}>Companies</a><a href="#intelligence" onClick={()=>setMenuOpen(false)}>Intelligence</a><a href="#newsletter" onClick={()=>setMenuOpen(false)}>Newsletter</a><a className="nav-employer" href="#employers" onClick={()=>setMenuOpen(false)}>For employers</a></nav><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle menu"><span/><span/></button></header>

    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow light">The Canadian capital-markets job board</p><h1>Find your next seat<br/>on Bay Street.</h1><p>Curated roles, firms and career intelligence for people building careers in Canadian finance.</p></div><div className="hero-stat"><strong>15</strong><span>active opportunities<br/>reviewed by BSO</span></div><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/></section>

    <section className="filter-wrap" aria-label="Search jobs"><div className="search-band"><Search size={22}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search role, firm, division or city" aria-label="Search jobs"/><span>{filtered.length} roles</span></div><div className="select-row"><label><span>Field</span><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(v=><option key={v}>{v}</option>)}</select><ChevronDown size={15}/></label><label><span>Type</span><select value={program} onChange={e=>setProgram(e.target.value)}>{programs.map(v=><option key={v}>{v}</option>)}</select><ChevronDown size={15}/></label>{companyFilter&&<span className="active-filter">{companyFilter}</span>}{(query||category!=="All fields"||program!=="All roles"||companyFilter)&&<button onClick={reset}><X size={14}/> Clear</button>}</div></section>

    <section className="featured-section"><Reveal className="section-heading"><div><p className="eyebrow">BSO selects</p><h2>Opportunities to watch.</h2></div><p>High-interest roles with approaching deadlines, selected for relevance to Canada&apos;s capital-markets community.</p></Reveal><div className="featured-grid">{jobs.slice(0,3).map((job,i)=><Reveal key={job.title} delay={i*90}><article className="featured-card" onClick={()=>setSelected(job)}><div className="featured-top"><CompanyLogo company={job.company} size="large"/><span>0{i+1}</span></div><p className="company-name">{job.company}</p><h3>{job.title}</h3><div className="featured-bottom"><span><Clock3 size={15}/>{fmt(job.deadline)}</span><ArrowUpRight/></div></article></Reveal>)}</div></section>

    <section className="jobs-section" id="jobs"><Reveal className="jobs-aside"><p className="eyebrow">All opportunities</p><h2>{companyFilter?`Roles at ${companyFilter}`:"The market, organized."}</h2><p>Every role links directly to the employer. Use search and filters to narrow the list.</p></Reveal><div className="job-list">{filtered.map((job,i)=><Reveal key={`${job.company}-${job.title}`} delay={Math.min(i,5)*35}><article className="job-card" onClick={()=>setSelected(job)}><CompanyLogo company={job.company}/><div className="job-copy"><p className="company-name">{job.company}</p><h3>{job.title}</h3><div className="meta"><span><MapPin size={14}/>{job.location}</span><span><BriefcaseBusiness size={14}/>{job.program}</span></div></div><span className="category">{job.category}</span><div className="job-action"><p>{job.deadline?"Apply by":"Deadline"}<strong>{fmt(job.deadline)}</strong></p><button>View <ArrowUpRight size={15}/></button></div></article></Reveal>)}{!filtered.length&&<div className="empty">No opportunities match those filters.</div>}</div></section>

    <section className="companies-section" id="companies"><Reveal className="section-heading inverse"><div><p className="eyebrow light">Explore the street</p><h2>Find roles by firm.</h2></div><p>Move beyond a list of openings. Explore the institutions shaping Canadian finance and see who is hiring now.</p></Reveal><div className="company-grid">{companies.map((company,i)=><Reveal key={company.name} delay={(i%4)*55}><button className="company-card" onClick={()=>chooseCompany(company.name)}><CompanyLogo company={company.name} size="large"/><div><h3>{company.name}</h3><p>{company.type}</p></div><span>{company.count} {company.count===1?"role":"roles"}</span><ArrowRight/></button></Reveal>)}</div></section>

    <section className="intelligence-section" id="intelligence"><Reveal className="section-heading"><div><p className="eyebrow">Career intelligence</p><h2>Know the market.<br/>Then enter it.</h2></div><p>Original BSO reporting translates the people, deals and recruiting patterns of Bay Street into an advantage.</p></Reveal><div className="stories"><Reveal><article className="lead-story"><span className="story-number">01</span><div><p className="eyebrow">Recruiting guide</p><h3>Inside the Winter 2027 recruiting cycle</h3><p>What opened, what is closing and where candidates should focus this week.</p><a href="#newsletter">Read in the next briefing <ArrowRight size={16}/></a></div></article></Reveal><Reveal delay={100}><article className="story"><span>02</span><div><p>People</p><h3>The conversations shaping Canadian capital markets</h3></div></article><article className="story"><span>03</span><div><p>Market map</p><h3>Who is hiring across Bay Street right now</h3></div></article></Reveal></div></section>

    <section className="newsletter-section" id="newsletter"><Reveal><div className="newsletter-inner"><div className="newsletter-icon"><Mail/></div><div><p className="eyebrow light">The BSO briefing</p><h2>The roles and intelligence that matter—once a week.</h2><p>Join 600+ readers across Canada&apos;s capital-markets community.</p></div><form onSubmit={e=>{e.preventDefault();setSubscribed(true)}}>{subscribed?<p className="signup-success" aria-live="polite">You&apos;re on the list. Welcome to BSO.</p>:<><input type="email" placeholder="Your email address" aria-label="Email address" required/><button>Join the briefing <ArrowRight size={17}/></button><small>Free. High signal. Unsubscribe anytime.</small></>}</form></div></Reveal></section>

    <section className="employer-section" id="employers"><Reveal className="employer-copy"><p className="eyebrow">For employers</p><h2>Reach Canada&apos;s next generation of finance talent.</h2><p>Put an opportunity in front of BSO&apos;s focused audience across the job board, newsletter and social channels.</p><a href="mailto:info@baystreetoracle.ca?subject=BSO%20Hiring%20Campaign">Start a hiring campaign <ArrowUpRight size={17}/></a></Reveal><Reveal delay={100} className="employer-card"><div><Sparkles/><span>BSO Hiring Campaign</span></div><ul><li>Featured homepage placement</li><li>Newsletter inclusion</li><li>Social distribution</li><li>Campaign performance report</li></ul><p>Built for banks, boutiques and financial institutions hiring in Canada.</p></Reveal></section>

    <footer><a className="footer-brand" href="#top"><img src="/bso-logo.png" alt=""/><span>THE BAY STREET ORACLE</span></a><div><a href="#jobs">Jobs</a><a href="#companies">Companies</a><a href="#intelligence">Intelligence</a><a href="#newsletter">Newsletter</a></div><div><p>Not NYC.<br/>Not trying to be.</p><a href="mailto:info@baystreetoracle.ca">info@baystreetoracle.ca</a></div><small>© 2026 The Bay Street Oracle</small></footer>

    {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="job-modal" onClick={e=>e.stopPropagation()} role="dialog" aria-modal="true"><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Close"><X/></button><CompanyLogo company={selected.company} size="large"/><p className="eyebrow">{selected.company}</p><h2>{selected.title}</h2><div className="modal-meta"><span><MapPin size={15}/>{selected.location}</span><span><BriefcaseBusiness size={15}/>{selected.program}</span></div><p className="modal-summary">{selected.summary}</p><dl><div><dt>Field</dt><dd>{selected.category}</dd></div><div><dt>Level</dt><dd>{selected.seniority}</dd></div><div><dt>Deadline</dt><dd>{fmt(selected.deadline)}</dd></div></dl><a className="apply-button" href={selected.url} target="_blank" rel="noreferrer">Apply on employer site <ArrowUpRight size={18}/></a></section></div>}
  </main>;
}
