-- Publish four employer-verified investment roles identified on October 8, 2026.
-- RBC replaces Anson Funds in the editorial featured lineup. Anson remains an
-- active BSO Exclusive listing in Current Opportunities.

WITH incoming AS (
  SELECT *
  FROM jsonb_to_recordset($jobs$
  [
    {
      "external_job_id": "R-0000189896",
      "company_id": "rbc-capital-markets",
      "company_name": "RBC Capital Markets",
      "title": "Analyst, Global Investment Banking - Mining & Metals",
      "location_display": "Toronto, ON",
      "city": "Toronto",
      "province": "ON",
      "country": "Canada",
      "category": "Investment Banking",
      "specialization": "Mining & Metals",
      "seniority": "Analyst",
      "employment_type": "Full-time",
      "program_type": "Full-time",
      "term_start": null,
      "term_end": null,
      "term_length_months": null,
      "date_posted": "2026-10-07",
      "application_deadline": "2026-11-05",
      "application_url": "https://rbc.wd3.myworkdayjobs.com/RBCGLOBAL1/job/TORONTO-Ontario-Canada/Analyst--Global-Investment-Banking---Mining---Metals_R-0000189896-1/apply",
      "source_url": "https://jobs.rbc.com/ca/en/job/RBCAA0088R0000189896EXTERNALENCA/Analyst-Global-Investment-Banking-Mining-and-Metals",
      "source_name": "RBC Capital Markets public careers site",
      "status": "active",
      "summary": "Full-time Analyst role with RBC Capital Markets' Mining & Metals investment banking team in Toronto.",
      "description_text": "RBC Capital Markets is hiring an Analyst for its Global Investment Banking Mining & Metals team in Toronto. The role develops and maintains financial models, supports transaction structuring and execution, analyzes companies and industries, prepares client presentations, conducts due diligence, and assists with equity and debt financings, mergers and acquisitions, and other advisory assignments. Candidates should have relevant experience in investment banking, private equity, equity research, corporate development or accounting, together with strong financial-modelling, analytical and communication skills. A university degree in finance, accounting, engineering or another quantitative discipline is preferred. Applicants must submit a cover letter, resume and academic transcripts through RBC's application portal by November 5, 2026.",
      "source_record_id": "rbc:R-0000189896",
      "data_quality_notes": "Role-specific Investment Banking evidence found in the employer title and description. Employer source and application deadline verified October 8, 2026."
    },
    {
      "external_job_id": "JR00868",
      "company_id": "cpp-investments",
      "company_name": "CPP Investments",
      "title": "Principal, Sustainable Energies & Infrastructure Credit",
      "location_display": "Toronto, ON",
      "city": "Toronto",
      "province": "ON",
      "country": "Canada",
      "category": "Private Credit",
      "specialization": "Sustainable Energies & Infrastructure Credit",
      "seniority": "Director",
      "employment_type": "Full-time",
      "program_type": "Full-time",
      "term_start": null,
      "term_end": null,
      "term_length_months": null,
      "date_posted": "2026-10-07",
      "application_deadline": "2026-11-08",
      "application_url": "https://cppib.wd10.myworkdayjobs.com/cppinvestments/job/Toronto/Principal--Sustainable-Energies---Infrastructure-Credit_JR00868-1",
      "source_url": "https://cppib.wd10.myworkdayjobs.com/cppinvestments/job/Toronto/Principal--Sustainable-Energies---Infrastructure-Credit_JR00868-1",
      "source_name": "CPP Investments public careers site",
      "status": "active",
      "summary": "Principal role with CPP Investments' Sustainable Energies & Infrastructure Credit team in Toronto, focused on private-credit origination and execution.",
      "description_text": "CPP Investments is hiring a Principal for its Sustainable Energies & Infrastructure Credit team in Toronto. The role originates, evaluates, underwrites, executes and manages private-credit investments across energy and infrastructure, with a focus on North American opportunities. Responsibilities include leading due diligence and transaction execution, preparing investment-committee recommendations, negotiating investment terms, monitoring portfolio positions, developing market relationships and mentoring junior team members. The employer requests at least eight years of relevant investing, investment banking or credit experience, strong financial-modelling and credit-underwriting skills, and experience executing complex energy or infrastructure transactions. Applications are accepted through CPP Investments' Workday site through November 8, 2026.",
      "source_record_id": "cpp-investments:JR00868",
      "data_quality_notes": "Employer description establishes direct private-credit origination, underwriting, execution and portfolio-management responsibility. Principal is normalized to Director under the public BSO seniority taxonomy. Verified October 8, 2026."
    },
    {
      "external_job_id": "R5004",
      "company_id": "psp-investments",
      "company_name": "PSP Investments",
      "title": "Intern, Natural Resources Investments, Latin America (January - April 2027)",
      "location_display": "Montreal, QC",
      "city": "Montreal",
      "province": "QC",
      "country": "Canada",
      "category": "Private Equity",
      "specialization": "Natural Resources",
      "seniority": "Intern",
      "employment_type": "Full-time",
      "program_type": "Internship",
      "term_start": "2027-01-01",
      "term_end": "2027-04-30",
      "term_length_months": 4,
      "date_posted": "2026-10-07",
      "application_deadline": null,
      "application_url": "https://investpsp.wd3.myworkdayjobs.com/psp_careers/job/Montreal/Intern--Natural-Resources-Investments--Latin-America--January---April-2027-_R5004",
      "source_url": "https://investpsp.wd3.myworkdayjobs.com/psp_careers/job/Montreal/Intern--Natural-Resources-Investments--Latin-America--January---April-2027-_R5004",
      "source_name": "PSP Investments public careers site",
      "status": "active",
      "summary": "January-to-April 2027 internship with PSP Investments' Natural Resources team in Montreal, supporting private-equity investments in Latin America.",
      "description_text": "PSP Investments is hiring an Intern for its Natural Resources Investments team in Montreal for a four-month term from January through April 2027. The role supports the evaluation of private-equity opportunities in Latin America through industry and company research, financial modelling, valuation, due diligence, investment-committee materials and portfolio-company analysis. Candidates must be enrolled in a university or master's program and should have strong analytical, financial-modelling and communication skills. Professional proficiency in English and Spanish is required, and Portuguese is an asset. The employer requests a resume, cover letter and most recent transcript through its Workday application.",
      "source_record_id": "psp-investments:R5004",
      "data_quality_notes": "Employer description establishes direct private-equity transaction analysis and portfolio-management support within Natural Resources Investments. Verified October 8, 2026."
    },
    {
      "external_job_id": "R4997",
      "company_id": "psp-investments",
      "company_name": "PSP Investments",
      "title": "Senior Analyst, Canada Growth Fund Investment Management (Calgary)",
      "location_display": "Calgary, AB",
      "city": "Calgary",
      "province": "AB",
      "country": "Canada",
      "category": "Asset Management",
      "specialization": "Energy Transition & Infrastructure",
      "seniority": "Analyst",
      "employment_type": "Full-time",
      "program_type": "Full-time",
      "term_start": null,
      "term_end": null,
      "term_length_months": null,
      "date_posted": "2026-10-07",
      "application_deadline": null,
      "application_url": "https://investpsp.wd3.myworkdayjobs.com/psp_careers/job/Calgary/Senior-Analyst--Canada-Growth-Fund-Investment-Management--Calgary-_R4997",
      "source_url": "https://investpsp.wd3.myworkdayjobs.com/psp_careers/job/Calgary/Senior-Analyst--Canada-Growth-Fund-Investment-Management--Calgary-_R4997",
      "source_name": "PSP Investments public careers site",
      "status": "active",
      "summary": "Senior Analyst role with PSP Investments' Canada Growth Fund team in Calgary, supporting investments across energy transition and infrastructure.",
      "description_text": "PSP Investments is hiring a Senior Analyst for Canada Growth Fund Investment Management in Calgary. The role participates across the investment process, including market research, opportunity origination, financial analysis and modelling, due diligence, transaction execution, investment-committee materials and ongoing asset management. The mandate focuses on Canadian growth opportunities connected to energy transition, clean technology, infrastructure and critical minerals. Candidates should have two to three years of relevant experience in investing, investment banking, consulting or a related field, along with a university degree and strong analytical, modelling and communication skills. CFA, CPA, CBV or MBA credentials are considered assets.",
      "source_record_id": "psp-investments:R4997",
      "data_quality_notes": "Employer description establishes direct investment research, underwriting, execution and asset-management responsibility. Senior Analyst is normalized to Analyst under the public BSO seniority taxonomy. Verified October 8, 2026."
    }
  ]$jobs$::jsonb)
  AS job(
    external_job_id text,
    company_id text,
    company_name text,
    title text,
    location_display text,
    city text,
    province text,
    country text,
    category text,
    specialization text,
    seniority text,
    employment_type text,
    program_type text,
    term_start text,
    term_end text,
    term_length_months integer,
    date_posted text,
    application_deadline text,
    application_url text,
    source_url text,
    source_name text,
    status text,
    summary text,
    description_text text,
    source_record_id text,
    data_quality_notes text
  )
)
INSERT INTO public.jobs (
  external_job_id, company_id, company_name, title, location_display, city, province, country,
  category, specialization, seniority, employment_type, program_type,
  term_start, term_end, term_length_months, date_posted, application_deadline,
  application_url, source_url, source_name, status, summary, description_text,
  description_status, description_verified_at, source_record_id, data_quality_notes,
  last_verified_at, updated_at
)
SELECT
  external_job_id,
  company_id,
  company_name,
  title,
  location_display,
  city,
  province,
  country,
  category,
  specialization,
  seniority,
  employment_type,
  program_type,
  nullif(term_start, '')::date,
  nullif(term_end, '')::date,
  term_length_months,
  nullif(date_posted, '')::date,
  nullif(application_deadline, '')::date,
  application_url,
  source_url,
  source_name,
  status,
  summary,
  description_text,
  'verified',
  now(),
  source_record_id,
  data_quality_notes,
  now(),
  now()
FROM incoming
ON CONFLICT (source_record_id) DO UPDATE SET
  company_id = EXCLUDED.company_id,
  company_name = EXCLUDED.company_name,
  title = EXCLUDED.title,
  location_display = EXCLUDED.location_display,
  city = EXCLUDED.city,
  province = EXCLUDED.province,
  country = EXCLUDED.country,
  category = EXCLUDED.category,
  specialization = EXCLUDED.specialization,
  seniority = EXCLUDED.seniority,
  employment_type = EXCLUDED.employment_type,
  program_type = EXCLUDED.program_type,
  term_start = EXCLUDED.term_start,
  term_end = EXCLUDED.term_end,
  term_length_months = EXCLUDED.term_length_months,
  date_posted = EXCLUDED.date_posted,
  application_deadline = EXCLUDED.application_deadline,
  application_url = EXCLUDED.application_url,
  source_url = EXCLUDED.source_url,
  source_name = EXCLUDED.source_name,
  status = EXCLUDED.status,
  summary = EXCLUDED.summary,
  description_text = EXCLUDED.description_text,
  description_status = EXCLUDED.description_status,
  description_verified_at = EXCLUDED.description_verified_at,
  data_quality_notes = EXCLUDED.data_quality_notes,
  last_verified_at = EXCLUDED.last_verified_at,
  updated_at = now();

UPDATE public.jobs
SET featured = false, updated_at = now()
WHERE source_record_id = 'bso-exclusive:anson-investment-analyst-2026-09';

UPDATE public.jobs
SET featured = true, updated_at = now()
WHERE source_record_id = 'rbc:R-0000189896';
