-- Publish the five employer-verified roles approved on October 4, 2026.
-- Also closes the stale BDO director posting and standardizes the Brookfield
-- private-equity title/summary. Featured status remains editorially controlled.

WITH incoming AS (
  SELECT *
  FROM jsonb_to_recordset($jobs$
  [
    {
      "external_job_id": "10008",
      "company_id": "stifel-canada",
      "company_name": "Stifel Canada",
      "title": "Vice President, Investment Banking - Diversified Industries",
      "location_display": "Toronto, ON",
      "city": "Toronto",
      "province": "ON",
      "country": "Canada",
      "category": "Investment Banking",
      "specialization": "Diversified Industries",
      "seniority": "Vice President",
      "employment_type": "Full-time",
      "program_type": "Full-time",
      "date_posted": "2026-10-02",
      "salary_min": null,
      "salary_max": null,
      "salary_currency": null,
      "salary_period": null,
      "application_url": "https://join.stifel.com/jobs/10008?lang=en-us",
      "source_url": "https://join.stifel.com/jobs/10008?lang=en-us",
      "source_name": "Stifel Canada public careers site",
      "status": "active",
      "summary": "Full-time Vice President role with Stifel Canada's Diversified Industries investment banking team in Toronto.",
      "description_text": "Stifel Canada is hiring a Vice President for its Diversified Industries investment banking team in Toronto. The role supports senior investment bankers, manages client relationships and live transactions, supervises financial modelling and valuation analysis, leads transaction workstreams, prepares client presentations and transaction documents, and mentors Associates. The position is office-based in Toronto. Candidates should have an undergraduate business degree with a finance focus; an MBA, CFA or CPA is preferred. Stifel requires at least six years of full-time experience in investment banking, corporate finance, accounting or private equity, along with strong financial analysis, communication, execution and team-management skills. Experience with Excel, PowerPoint, Word, Bloomberg, FactSet and Capital IQ is relevant to the role.",
      "source_record_id": "stifel-canada:10008",
      "data_quality_notes": "Role-specific Investment Banking evidence found in the employer title and description. Verified through Stifel Canada's public iCIMS Jibe feed on October 4, 2026."
    },
    {
      "external_job_id": "10009",
      "company_id": "stifel-canada",
      "company_name": "Stifel Canada",
      "title": "Analyst, Investment Banking - Diversified Industries",
      "location_display": "Toronto, ON",
      "city": "Toronto",
      "province": "ON",
      "country": "Canada",
      "category": "Investment Banking",
      "specialization": "Diversified Industries",
      "seniority": "Analyst",
      "employment_type": "Full-time",
      "program_type": "Full-time",
      "date_posted": "2026-10-02",
      "salary_min": 100000,
      "salary_max": 100000,
      "salary_currency": "CAD",
      "salary_period": "year",
      "application_url": "https://join.stifel.com/jobs/10009?lang=en-us",
      "source_url": "https://join.stifel.com/jobs/10009?lang=en-us",
      "source_name": "Stifel Canada public careers site",
      "status": "active",
      "summary": "Full-time Analyst role with Stifel Canada's Diversified Industries investment banking team in Toronto.",
      "description_text": "Stifel Canada is hiring an Investment Banking Analyst for its Diversified Industries team in Toronto. The role supports valuation work, financial modelling, company and industry research, client presentations, due diligence and the execution of financing, private-equity and M&A transactions. As experience develops, the Analyst is expected to assume more responsibility on live transactions and interact directly with clients. The position is office-based in Toronto and has a stated annual base salary of CAD 100,000. Candidates should have an undergraduate business degree with a finance focus. One to two years of internship, co-op or full-time experience in corporate finance, investment banking, accounting or private equity is considered beneficial. Strong financial analysis, attention to detail, communication, problem-solving and Microsoft Office skills are required.",
      "source_record_id": "stifel-canada:10009",
      "data_quality_notes": "Role-specific Investment Banking evidence found in the employer title and description. Salary is employer disclosed. Verified through Stifel Canada's public iCIMS Jibe feed on October 4, 2026."
    },
    {
      "external_job_id": "10006",
      "company_id": "stifel-canada",
      "company_name": "Stifel Canada",
      "title": "Associate, Investment Banking - Diversified Industries",
      "location_display": "Toronto, ON",
      "city": "Toronto",
      "province": "ON",
      "country": "Canada",
      "category": "Investment Banking",
      "specialization": "Diversified Industries",
      "seniority": "Associate",
      "employment_type": "Full-time",
      "program_type": "Full-time",
      "date_posted": "2026-10-02",
      "salary_min": 135000,
      "salary_max": 135000,
      "salary_currency": "CAD",
      "salary_period": "year",
      "application_url": "https://join.stifel.com/jobs/10006?lang=en-us",
      "source_url": "https://join.stifel.com/jobs/10006?lang=en-us",
      "source_name": "Stifel Canada public careers site",
      "status": "active",
      "summary": "Full-time Associate role with Stifel Canada's Diversified Industries investment banking team in Toronto.",
      "description_text": "Stifel Canada is hiring an Investment Banking Associate for its Diversified Industries team in Toronto. The role supports senior investment bankers through client presentations, company and industry research, financial modelling, transaction execution and Analyst mentorship. Responsibilities include developing pitches, leading transaction workstreams, performing due diligence, building M&A and capital-raising models, presenting to senior executives, maintaining market-comparable databases and developing client relationships. The position is office-based in Toronto and has a stated annual base salary of CAD 135,000. Candidates should have an undergraduate business degree with a finance focus and at least three years of full-time experience in corporate finance, investment banking, accounting or private equity. An MBA, CFA or CPA is preferred, along with strong financial analysis, communication and Microsoft Office skills.",
      "source_record_id": "stifel-canada:10006",
      "data_quality_notes": "Role-specific Investment Banking evidence found in the employer title and description. Salary is employer disclosed. Verified through Stifel Canada's public iCIMS Jibe feed on October 4, 2026."
    },
    {
      "external_job_id": "34158",
      "company_id": "kpmg-corporate-finance",
      "company_name": "KPMG Corporate Finance",
      "title": "Senior Manager, Turnaround & Restructuring - Deal Advisory",
      "location_display": "Toronto, ON",
      "city": "Toronto",
      "province": "ON",
      "country": "Canada",
      "category": "Corporate Finance",
      "specialization": "Restructuring",
      "seniority": "Associate",
      "employment_type": "Full-time",
      "program_type": "Full-time",
      "date_posted": "2026-10-02",
      "salary_min": null,
      "salary_max": null,
      "salary_currency": null,
      "salary_period": null,
      "application_url": "https://careers.kpmg.ca/jobs/34158?lang=en-us",
      "source_url": "https://careers.kpmg.ca/jobs/34158?lang=en-us",
      "source_name": "KPMG Corporate Finance public careers site",
      "status": "active",
      "summary": "Senior Manager role with KPMG Deal Advisory's Turnaround & Restructuring team in Toronto, advising distressed companies and stakeholders.",
      "description_text": "KPMG is hiring a Senior Manager for its Turnaround & Restructuring team within Deal Advisory in Toronto. The group advises companies, lenders, boards, regulators and other stakeholders through underperformance, liquidity pressure, refinancing, turnaround planning and formal insolvency proceedings. The role leads teams and client engagements, develops restructuring strategies and turnaround plans, reviews complex financial models and cash-flow forecasts, manages CCAA and Bankruptcy and Insolvency Act proceedings, coordinates stakeholders and external advisors, and contributes to business development and practice management. Candidates should have at least five years of restructuring and insolvency experience, including one to two years at a senior-manager or equivalent level. CIRP and Licensed Insolvency Trustee credentials, strong financial modelling and negotiation skills, and the ability to lead simultaneous advisory engagements and formal proceedings are required.",
      "source_record_id": "kpmg-cf:34158",
      "data_quality_notes": "Corporate Finance classification follows BSO's taxonomy for Deal Advisory firms. Employer title and description establish direct turnaround and restructuring advisory responsibility. Verified through KPMG Canada's public iCIMS Jibe feed on October 4, 2026."
    },
    {
      "external_job_id": "JR7164",
      "company_id": "bdo-ma",
      "company_name": "BDO M&A & Capital Markets",
      "title": "Senior Associate, Business Restructuring & Turnaround Services",
      "location_display": "Edmonton, AB",
      "city": "Edmonton",
      "province": "AB",
      "country": "Canada",
      "category": "Corporate Finance",
      "specialization": "Restructuring",
      "seniority": "Associate",
      "employment_type": "Full-time",
      "program_type": "Full-time",
      "date_posted": "2026-10-02",
      "salary_min": null,
      "salary_max": null,
      "salary_currency": null,
      "salary_period": null,
      "application_url": "https://bdo.wd3.myworkdayjobs.com/BDO/job/Edmonton---103-St/Senior-Associate--Business-Restructuring---Turnaround-Services_JR7164",
      "source_url": "https://bdo.wd3.myworkdayjobs.com/BDO/job/Edmonton---103-St/Senior-Associate--Business-Restructuring---Turnaround-Services_JR7164",
      "source_name": "BDO M&A & Capital Markets public careers site",
      "status": "active",
      "summary": "Senior Associate role with BDO's Corporate Restructuring group in Edmonton, supporting restructuring, insolvency and turnaround engagements.",
      "description_text": "BDO is hiring a Senior Associate for its Corporate Restructuring group in Edmonton. The role supports creditors and distressed businesses through receiverships, bankruptcies, operational stabilization, liquidity analysis, turnaround planning, asset sales and formal or informal financial restructurings. Responsibilities include analyzing financial records, assessing business plans and forecasts, building 13-week cash-flow and scenario models, preparing stakeholder and court reports, working with management teams, lenders and legal counsel, managing key engagement workstreams, and supporting distressed-asset and business sale processes. Candidates should have two to three years of experience in a professional accounting services firm and a CPA designation completed or in progress. Restructuring, insolvency or turnaround experience is an asset, and the employer expects interest in pursuing the CIRP designation. Strong financial analysis, modelling, communication and organizational skills are required.",
      "source_record_id": "bdo-ma:JR7164",
      "data_quality_notes": "Corporate Finance classification follows BSO's taxonomy for Deal Advisory firms. Employer title and description establish direct restructuring advisory responsibility. Verified through BDO Canada's public Workday feed on October 4, 2026."
    }
  ]$jobs$::jsonb)
  AS job(
    external_job_id text,
    company_id text,
    company_name text,
    title text,
    location_display text,
    city text,
    province text,
    country text,
    category text,
    specialization text,
    seniority text,
    employment_type text,
    program_type text,
    date_posted text,
    salary_min numeric,
    salary_max numeric,
    salary_currency text,
    salary_period text,
    application_url text,
    source_url text,
    source_name text,
    status text,
    summary text,
    description_text text,
    source_record_id text,
    data_quality_notes text
  )
)
INSERT INTO public.jobs (
  external_job_id, company_id, company_name, title, location_display, city, province, country,
  category, specialization, seniority, employment_type, program_type, date_posted,
  salary_min, salary_max, salary_currency, salary_period,
  application_url, source_url, source_name, status, summary, description_text,
  description_status, description_verified_at, source_record_id, data_quality_notes,
  last_verified_at, updated_at
)
SELECT
  external_job_id,
  company_id,
  company_name,
  title,
  location_display,
  city,
  province,
  country,
  category,
  specialization,
  seniority,
  employment_type,
  program_type,
  date_posted::date,
  salary_min,
  salary_max,
  salary_currency,
  salary_period,
  application_url,
  source_url,
  source_name,
  status,
  summary,
  description_text,
  'verified',
  now(),
  source_record_id,
  data_quality_notes,
  now(),
  now()
FROM incoming
ON CONFLICT (source_record_id) DO UPDATE SET
  company_id = EXCLUDED.company_id,
  company_name = EXCLUDED.company_name,
  title = EXCLUDED.title,
  location_display = EXCLUDED.location_display,
  city = EXCLUDED.city,
  province = EXCLUDED.province,
  country = EXCLUDED.country,
  category = EXCLUDED.category,
  specialization = EXCLUDED.specialization,
  seniority = EXCLUDED.seniority,
  employment_type = EXCLUDED.employment_type,
  program_type = EXCLUDED.program_type,
  date_posted = EXCLUDED.date_posted,
  salary_min = EXCLUDED.salary_min,
  salary_max = EXCLUDED.salary_max,
  salary_currency = EXCLUDED.salary_currency,
  salary_period = EXCLUDED.salary_period,
  application_url = EXCLUDED.application_url,
  source_url = EXCLUDED.source_url,
  source_name = EXCLUDED.source_name,
  status = EXCLUDED.status,
  summary = EXCLUDED.summary,
  description_text = EXCLUDED.description_text,
  description_status = EXCLUDED.description_status,
  description_verified_at = EXCLUDED.description_verified_at,
  data_quality_notes = EXCLUDED.data_quality_notes,
  last_verified_at = EXCLUDED.last_verified_at,
  updated_at = now();

UPDATE public.jobs
SET
  status = 'closed',
  featured = false,
  data_quality_notes = concat_ws(
    ' ',
    nullif(data_quality_notes, ''),
    'Closed October 4, 2026 after the role was absent from a completed authoritative BDO Workday scan.'
  ),
  last_verified_at = now(),
  updated_at = now()
WHERE source_record_id = 'bdo-ma:JR7113';

UPDATE public.jobs
SET
  title = 'Investment Associate, Private Equity',
  summary = 'Investment Associate role with Brookfield Asset Management''s private-equity team in Toronto, focused on evaluating, executing and monitoring investments.',
  updated_at = now()
WHERE source_record_id = 'brookfield-asset-management:R2052799';
