-- Add NewPoint Capital Partners' employer-submitted Summer 2027 role.

INSERT INTO public.companies (
  company_id,
  name,
  parent_company,
  company_type,
  website_domain,
  headquarters_country,
  status,
  notes,
  updated_at
)
VALUES (
  'newpoint-clairfield-canada',
  'NewPoint / Clairfield Canada',
  'Clairfield International',
  'Investment Bank',
  'newpoint.ca',
  'Canada',
  'active',
  'Toronto-based independent mid-market investment banking firm and Clairfield International member firm.',
  now()
)
ON CONFLICT (company_id) DO UPDATE SET
  name = EXCLUDED.name,
  parent_company = EXCLUDED.parent_company,
  company_type = EXCLUDED.company_type,
  website_domain = EXCLUDED.website_domain,
  headquarters_country = EXCLUDED.headquarters_country,
  status = EXCLUDED.status,
  notes = EXCLUDED.notes,
  updated_at = now();

INSERT INTO public.jobs (
  external_job_id,
  company_id,
  company_name,
  title,
  location_display,
  city,
  province,
  country,
  workplace_type,
  category,
  specialization,
  seniority,
  employment_type,
  program_type,
  term_start,
  term_end,
  term_length_months,
  date_posted,
  application_deadline,
  salary_min,
  salary_max,
  salary_currency,
  salary_period,
  application_url,
  source_url,
  source_name,
  status,
  featured,
  summary,
  description_text,
  description_status,
  description_verified_at,
  source_record_id,
  data_quality_notes,
  last_verified_at,
  updated_at
)
VALUES (
  'summer-2027-junior-analyst',
  'newpoint-clairfield-canada',
  'NewPoint / Clairfield Canada',
  'Junior Analyst, Investment Banking - Summer 2027',
  'Toronto, ON',
  'Toronto',
  'ON',
  'Canada',
  NULL,
  'Investment Banking',
  'Mid-Market M&A',
  'Intern',
  'Internship',
  'Co-op',
  '2027-05-01',
  '2027-08-31',
  4,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'https://newpoint.ca/careers/',
  'https://newpoint.ca/careers/',
  'NewPoint Capital Partners public careers site',
  'active',
  false,
  'Summer 2027 Investment Banking Junior Analyst co-op with NewPoint Capital Partners in Toronto, focused on mid-market M&A and corporate finance advisory.',
  'NewPoint Capital Partners is hiring a student as a Junior Investment Banking Analyst in Toronto for a four-month Summer 2027 co-op term running from May through August. NewPoint is an independent mid-market investment banking firm advising private companies and public-company divisions on divestitures, mergers and acquisitions, financings and restructurings, typically involving transactions between $10 million and $200 million. The role supports financial modelling, valuation analysis, pitches, confidential information memoranda, management presentations, buyer and target identification, industry research, marketing and business development. Candidates should demonstrate an interest in finance, strong analytical and communication skills, knowledge of accounting and finance concepts, and proficiency with Microsoft Office. Capital IQ and Salesforce experience are assets. Applicants must submit a cover letter, resume and transcript or academic record combined into one PDF through the employer''s careers page.',
  'verified',
  now(),
  'newpoint-capital-partners:summer-2027-junior-analyst',
  'Employer-submitted role verified against NewPoint Capital Partners'' public careers page on October 9, 2026. No application deadline or salary figure is published.',
  now(),
  now()
)
ON CONFLICT (source_record_id) DO UPDATE SET
  company_id = EXCLUDED.company_id,
  company_name = EXCLUDED.company_name,
  title = EXCLUDED.title,
  location_display = EXCLUDED.location_display,
  city = EXCLUDED.city,
  province = EXCLUDED.province,
  country = EXCLUDED.country,
  workplace_type = EXCLUDED.workplace_type,
  category = EXCLUDED.category,
  specialization = EXCLUDED.specialization,
  seniority = EXCLUDED.seniority,
  employment_type = EXCLUDED.employment_type,
  program_type = EXCLUDED.program_type,
  term_start = EXCLUDED.term_start,
  term_end = EXCLUDED.term_end,
  term_length_months = EXCLUDED.term_length_months,
  date_posted = EXCLUDED.date_posted,
  application_deadline = EXCLUDED.application_deadline,
  salary_min = EXCLUDED.salary_min,
  salary_max = EXCLUDED.salary_max,
  salary_currency = EXCLUDED.salary_currency,
  salary_period = EXCLUDED.salary_period,
  application_url = EXCLUDED.application_url,
  source_url = EXCLUDED.source_url,
  source_name = EXCLUDED.source_name,
  status = EXCLUDED.status,
  summary = EXCLUDED.summary,
  description_text = EXCLUDED.description_text,
  description_status = EXCLUDED.description_status,
  description_verified_at = EXCLUDED.description_verified_at,
  data_quality_notes = EXCLUDED.data_quality_notes,
  last_verified_at = EXCLUDED.last_verified_at,
  updated_at = now();
